### ISSUE TITLE
error on bootstrap collapse: undefined is not a function

### ISSUE THREAD

**Issue by isatimur** [simonexmachina/tabcordion#2]
Hello, I'm working with bootstrap.js v3.2.0 and jquery v1.8.3, and stuck on error at bootstrap Collapse plugin it's refering that error appear on this line:
<code>  if (typeof option == 'string') data[option]()</code>
Error: undefined is not a function

Do you have any idea how to fix this problems.
Steps to reproduce:
open page with exapmle of tabcordion-> narrow the browser->click on some titles-> extend browser to first state and error should appear on browser console.
Thx in advance!
Timur Isa

**Comment by vallieres** [comment]
Same error here, but with Bootstrap 3.3.4 and jQuery 1.10.2.

    TypeError: data[option] is not a function

**Comment by vallieres** [comment]
@isatimur did you find a solution?

**Comment by vallieres** [comment]
Tested with Bootstrap 3.3.4 (latest) and jQuery 1.10
http://jsfiddle.net/vallieres/qjfvbj7o/

Tested with Bootstrap 3.3.4 (latest) and jQuery 2.1.3 (latest)
http://jsfiddle.net/vallieres/b9vrpdon/

Both have the issue. 

To reproduce:
Load page (full page result is best), open console. Resize window to smaller width, watch the library change the tabs to accordion. Then when you pull back the window to a desktop size. You get this error in the log:

    Uncaught TypeError: data[option] is not a function

Emanating from line 705 of bootstrap.js

    function Plugin(option) {
      return this.each(function () {
        var $this   = $(this)
        var data    = $this.data('bs.collapse')
        var options = $.extend({}, Collapse.DEFAULTS, $this.data(), typeof option == 'object' && option)

        if (!data && options.toggle && /show|hide/.test(option)) options.toggle = false
        if (!data) $this.data('bs.collapse', (data = new Collapse(this, options)))
        if (typeof option == 'string') data[option]() /*   <=== This line   */
      })
    }

**Comment by vallieres** [comment]
ah well, I fixed it! You can find the solution in this pull request:

https://github.com/aexmachina/tabcordion/pull/3

**Comment by isatimur** [comment]
@vallieres thank you for your solution!
